[build]
  command   = "npm run build"
  publish   = "dist"

# Redirect all 404s to index.html so that client-side routing (if any) works.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
